version: "3"
services:
  api:
    image: reekithak2/learn_fastapi_api
    depends_on:
      - postgres
    ports:
      - 80:8000  # <port on localhost>:<port on docker container>
#    volumes:
#      - ./:/usr/src/app:ro # ro is read only, for extra security.
#    command:
#      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # To reload the server everytime there's a change
#    env_file:
#      - ./app/.env
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - USERNAME=${USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:

