name: Build and Deploy Code

on:
  push:
    branches:
      - "main"
      - "anotherbranch"
  pull_request:
    branches:
      - "test_branch"
jobs:
  job1:
    env:
    DB_HOSTNAME=localhost
    DB_PORT=5432
    DB_PASSWORD=123456
    DB_NAME=fastapi
    USERNAME=postgres
    SECRET_KEY=09bhdfgvdhfdbn873bgv784bhb4802ub3h4888230
    ALGORITHM=HS256
    ACCESS_TOKEN_EXPIRE_MINUTES=100
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name:  Install Python v3.9
        uses:  actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name:  Installing packages
        run: pip install -r requirements.txt
      - name: Testing with pytest
        run: |
          pip install pytest
          pytest -v -s

